development:
  adapter: postgresql
  encoding: unicode
  database: missiondog
  pool: 5
  username: missiondog
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: missiondog_test
  pool: 5
  username: missiondog
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: missiondog
  pool: 5
  username: missiondog
  password: 
